language: ruby
rvm:
  - 2.2.0
script:
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate RAILS_ENV=test"
  - "bundle exec rspec spec"
env:
  - PG_USERNAME='postgres'

branches:
  only:
    - master

notifications:
  email:
    - igor.yuzovitskiy@gmail.com
    - alex.hint.ah@gmail.com