language: ruby
rvm:
- 2.2.0
script:
- bundle exec rake db:create
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rspec spec
env:
- PG_USERNAME='postgres'
branches:
  only:
  - master
  - qa
notifications:
  email:
  - igor.yuzovitskiy@gmail.com
  - alex.hint.ah@gmail.com
  slack:
    secure: CagOptA8PiBHHra+CT4+7U/4iPruiaCI7BTmsbCcJ2Nlb89Z1DH/aEeQJstUf1jl8UWVG+VNPjV1Jzvc1vyxvQgblH/VrqSLa/KR9lRy9qgrFNimWivbUIxMcN7rPWcFWj/lbQGbYmc3fQtDRdD4rLNzIa1LuCUTgHh77XweNUY=
deploy:
  provider: heroku
  api_key:
    master:
      secure: qeLhyeEkpSrKIAc7reJkXqeNMM/rM2br1xAafnTh29dxyU4K7zraxdC27GWNwJilaPWs9juinHQXSEMGHJnhuEiGB7dIBnAB4QTEyQpTuaq8CNr0ud523p6Fsu7TRe8I/KZZM8jPaiIWT9vzF7BIR9EMR5/eic2Rm3zG8V0a2k4=
    qa:
      secure: XgqG4dHHe0LkfaqENfUzw2+6a9A8ipeLr9xLx3WI1JzBspSefw88fKDUrtFchevhCwRKw7363cyLFbndOA1SBqSka0ZQrhx99KcTP0SbKmD6ZlwL7Fl0GlncXsRi3ChPe2Lk/hQcmhMfsScXxXJlPx/6FDxr1rYdjNcI8W9Jf24=
  app:
    master: flowlist
    qa: qa-flowlist