# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6cb75f70c9ce0bb0256ac2e3ec61837d491c272ab975bc2ac9fef4aa30470b1d2a45f78e4b3efba8355f1f3568944a72c6f606c9b8c2eb9e7efa02e147d5444

test:
  secret_key_base: 27d4408318d4c09c28fabae3063a25bf178333e15cd7c6da300bc013c56f0f7d3a8ba44cf85382a61af9d98c764e5b7404e26ea6a41ba99d51ff88ac2dfa88a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
